import {
  Activity, AlarmClock, Apple, Baby, Battery, BatteryCharging, BatteryLow,
  BatteryMedium, BatteryWarning, Bike, BookOpen, Brain, Briefcase, Brush,
  Camera, Car, CheckCircle, Circle, CircleCheck, CircleMinus, CirclePlus,
  CircleX, ClipboardList, Clock, Cloud, CloudLightning,
  CloudMoon, CloudRain, CloudSun, Code, Coffee, Crown, DollarSign, Droplets,
  Dumbbell, Eye, FileText, Film, Flame, Flower, Flower2, Footprints, Frown,
  Gamepad2, Ghost, Gift, Globe, GraduationCap, Hammer, Handshake, Headphones,
  Heart, HeartCrack, HeartHandshake, HeartOff, HeartPulse, HelpCircle, Home,
  Laptop, Laugh, Leaf, Lightbulb, Link, Lock, Map, MapPin, Meh, MessageCircle,
  Moon, MoonStar, Mountain, MoveHorizontal, Music, Network, Notebook, Package,
  Palette, PauseCircle, Pencil, PersonStanding, Phone, Pill, Pizza, Plane,
  Rocket, Scissors, Shield, ShoppingBag, Skull, Smile, SmilePlus, Snowflake,
  Sofa, Sparkles, Sprout, Star, Stars, Stethoscope, Sun, SunMedium, Sunrise,
  Sunset, Tag, Target, Thermometer, ThermometerSnowflake, ThumbsDown, ThumbsUp,
  Timer, TreePine, Trees, Trophy, Tv, UtensilsCrossed, Utensils, UserMinus,
  UserPlus, Users, Waves, Wind, Wine, Wrench, Zap, ZapOff,
  type LucideIcon,
} from 'lucide-react-native';

export type IconComponent = LucideIcon;

export interface IconEntry {
  name: string;
  component: IconComponent;
  label: string;
}

export const AVAILABLE_ICONS: IconEntry[] = [
  { name: 'Activity', component: Activity, label: 'Activity' },
  { name: 'AlarmClock', component: AlarmClock, label: 'Alarm' },
  { name: 'Apple', component: Apple, label: 'Apple' },
  { name: 'Baby', component: Baby, label: 'Baby' },
  { name: 'Battery', component: Battery, label: 'Battery' },
  { name: 'BatteryCharging', component: BatteryCharging, label: 'Charging' },
  { name: 'BatteryLow', component: BatteryLow, label: 'Low battery' },
  { name: 'BatteryMedium', component: BatteryMedium, label: 'Half battery' },
  { name: 'BatteryWarning', component: BatteryWarning, label: 'Battery warn' },
  { name: 'Bike', component: Bike, label: 'Bike' },
  { name: 'BookOpen', component: BookOpen, label: 'Book' },
  { name: 'Brain', component: Brain, label: 'Brain' },
  { name: 'Briefcase', component: Briefcase, label: 'Briefcase' },
  { name: 'Brush', component: Brush, label: 'Draw' },
  { name: 'Camera', component: Camera, label: 'Camera' },
  { name: 'Car', component: Car, label: 'Car' },
  { name: 'CheckCircle', component: CheckCircle, label: 'Check circle' },
  { name: 'Circle', component: Circle, label: 'Circle' },
  { name: 'CircleCheck', component: CircleCheck, label: 'Done' },
  { name: 'CircleMinus', component: CircleMinus, label: 'Circle minus' },
  { name: 'CirclePlus', component: CirclePlus, label: 'Circle plus' },
  { name: 'CircleX', component: CircleX, label: 'Circle X' },
  { name: 'ClipboardList', component: ClipboardList, label: 'List' },
  { name: 'Clock', component: Clock, label: 'Clock' },
  { name: 'Cloud', component: Cloud, label: 'Cloud' },
  { name: 'CloudLightning', component: CloudLightning, label: 'Storm' },
  { name: 'CloudMoon', component: CloudMoon, label: 'Cloudy night' },
  { name: 'CloudRain', component: CloudRain, label: 'Rain' },
  { name: 'CloudSun', component: CloudSun, label: 'Partly cloudy' },
  { name: 'Code', component: Code, label: 'Code' },
  { name: 'Coffee', component: Coffee, label: 'Coffee' },
  { name: 'Crown', component: Crown, label: 'Crown' },
  { name: 'DollarSign', component: DollarSign, label: 'Money' },
  { name: 'Droplets', component: Droplets, label: 'Water' },
  { name: 'Dumbbell', component: Dumbbell, label: 'Workout' },
  { name: 'Eye', component: Eye, label: 'Eye' },
  { name: 'FileText', component: FileText, label: 'Document' },
  { name: 'Film', component: Film, label: 'Movie' },
  { name: 'Flame', component: Flame, label: 'Flame' },
  { name: 'Flower', component: Flower, label: 'Flower' },
  { name: 'Flower2', component: Flower2, label: 'Flower 2' },
  { name: 'Footprints', component: Footprints, label: 'Walk' },
  { name: 'Frown', component: Frown, label: 'Sad' },
  { name: 'Gamepad2', component: Gamepad2, label: 'Gaming' },
  { name: 'Ghost', component: Ghost, label: 'Ghost' },
  { name: 'Gift', component: Gift, label: 'Gift' },
  { name: 'Globe', component: Globe, label: 'Globe' },
  { name: 'GraduationCap', component: GraduationCap, label: 'Graduate' },
  { name: 'Hammer', component: Hammer, label: 'Hammer' },
  { name: 'Handshake', component: Handshake, label: 'Handshake' },
  { name: 'Headphones', component: Headphones, label: 'Headphones' },
  { name: 'Heart', component: Heart, label: 'Heart' },
  { name: 'HeartCrack', component: HeartCrack, label: 'Broken heart' },
  { name: 'HeartHandshake', component: HeartHandshake, label: 'Heart shake' },
  { name: 'HeartOff', component: HeartOff, label: 'Heart off' },
  { name: 'HeartPulse', component: HeartPulse, label: 'Heartbeat' },
  { name: 'HelpCircle', component: HelpCircle, label: 'Help' },
  { name: 'Home', component: Home, label: 'Home' },
  { name: 'Laptop', component: Laptop, label: 'Laptop' },
  { name: 'Laugh', component: Laugh, label: 'Laughing' },
  { name: 'Leaf', component: Leaf, label: 'Nature' },
  { name: 'Lightbulb', component: Lightbulb, label: 'Idea' },
  { name: 'Link', component: Link, label: 'Link' },
  { name: 'Lock', component: Lock, label: 'Lock' },
  { name: 'Map', component: Map, label: 'Map' },
  { name: 'MapPin', component: MapPin, label: 'Location' },
  { name: 'Meh', component: Meh, label: 'Meh' },
  { name: 'MessageCircle', component: MessageCircle, label: 'Chat' },
  { name: 'Moon', component: Moon, label: 'Moon' },
  { name: 'MoonStar', component: MoonStar, label: 'Moon star' },
  { name: 'Mountain', component: Mountain, label: 'Mountain' },
  { name: 'MoveHorizontal', component: MoveHorizontal, label: 'Stretch' },
  { name: 'Music', component: Music, label: 'Music' },
  { name: 'Network', component: Network, label: 'Network' },
  { name: 'Notebook', component: Notebook, label: 'Notebook' },
  { name: 'Package', component: Package, label: 'Package' },
  { name: 'Palette', component: Palette, label: 'Palette' },
  { name: 'PauseCircle', component: PauseCircle, label: 'Pause' },
  { name: 'Pencil', component: Pencil, label: 'Write' },
  { name: 'PersonStanding', component: PersonStanding, label: 'Person' },
  { name: 'Phone', component: Phone, label: 'Phone' },
  { name: 'Pill', component: Pill, label: 'Medicine' },
  { name: 'Pizza', component: Pizza, label: 'Food' },
  { name: 'Plane', component: Plane, label: 'Travel' },
  { name: 'Rocket', component: Rocket, label: 'Rocket' },
  { name: 'Scissors', component: Scissors, label: 'Scissors' },
  { name: 'Shield', component: Shield, label: 'Shield' },
  { name: 'ShoppingBag', component: ShoppingBag, label: 'Shopping' },
  { name: 'Skull', component: Skull, label: 'Skull' },
  { name: 'Smile', component: Smile, label: 'Smile' },
  { name: 'SmilePlus', component: SmilePlus, label: 'Happy+' },
  { name: 'Snowflake', component: Snowflake, label: 'Snow' },
  { name: 'Sofa', component: Sofa, label: 'Relax' },
  { name: 'Sparkles', component: Sparkles, label: 'Sparkles' },
  { name: 'Sprout', component: Sprout, label: 'Sprout' },
  { name: 'Star', component: Star, label: 'Star' },
  { name: 'Stars', component: Stars, label: 'Stars' },
  { name: 'Stethoscope', component: Stethoscope, label: 'Medical' },
  { name: 'Sun', component: Sun, label: 'Sun' },
  { name: 'SunMedium', component: SunMedium, label: 'Warm' },
  { name: 'Sunrise', component: Sunrise, label: 'Sunrise' },
  { name: 'Sunset', component: Sunset, label: 'Sunset' },
  { name: 'Tag', component: Tag, label: 'Tag' },
  { name: 'Target', component: Target, label: 'Target' },
  { name: 'Thermometer', component: Thermometer, label: 'Temp' },
  { name: 'ThermometerSnowflake', component: ThermometerSnowflake, label: 'Cold' },
  { name: 'ThumbsDown', component: ThumbsDown, label: 'Dislike' },
  { name: 'ThumbsUp', component: ThumbsUp, label: 'Like' },
  { name: 'Timer', component: Timer, label: 'Timer' },
  { name: 'TreePine', component: TreePine, label: 'Tree' },
  { name: 'Trees', component: Trees, label: 'Forest' },
  { name: 'Trophy', component: Trophy, label: 'Trophy' },
  { name: 'Tv', component: Tv, label: 'TV' },
  { name: 'UserMinus', component: UserMinus, label: 'Remove user' },
  { name: 'UserPlus', component: UserPlus, label: 'Add user' },
  { name: 'Users', component: Users, label: 'People' },
  { name: 'Utensils', component: Utensils, label: 'Eat' },
  { name: 'UtensilsCrossed', component: UtensilsCrossed, label: 'Restaurant' },
  { name: 'Waves', component: Waves, label: 'Waves' },
  { name: 'Wind', component: Wind, label: 'Wind' },
  { name: 'Wine', component: Wine, label: 'Wine' },
  { name: 'Wrench', component: Wrench, label: 'Tool' },
  { name: 'Zap', component: Zap, label: 'Energy' },
  { name: 'ZapOff', component: ZapOff, label: 'Tired' },
];

export const MOOD_ICONS: IconEntry[] = AVAILABLE_ICONS.filter((i) =>
  [
    'Smile', 'SmilePlus', 'Laugh', 'Meh', 'Frown', 'CircleMinus',
    'Heart', 'HeartCrack', 'HeartOff', 'HeartPulse', 'HeartHandshake',
    'Star', 'Stars', 'Sparkles',
    'Zap', 'ZapOff',
    'ThumbsUp', 'ThumbsDown',
    'Sun', 'SunMedium', 'Sunrise', 'Sunset',
    'Moon', 'MoonStar', 'CloudMoon',
    'Cloud', 'CloudRain', 'CloudSun', 'CloudLightning',
    'Snowflake', 'Thermometer', 'ThermometerSnowflake', 'Flame',
    'Battery', 'BatteryLow', 'BatteryMedium', 'BatteryCharging', 'BatteryWarning',
    'Rocket', 'Crown', 'Trophy', 'Skull', 'Ghost', 'Gamepad2',
    'Circle', 'CircleX', 'CirclePlus', 'CircleCheck', 'CheckCircle',
    'Sprout', 'Leaf', 'Trees', 'Flower', 'Flower2',
  ].includes(i.name)
);

export interface MoodIconSet {
  id: string;
  name: string;
  icons: Record<string, string>;
}

export const MOOD_ICON_SETS: MoodIconSet[] = [
  { id: 'facial', name: 'Facial expressions', icons: { '1': 'Frown', '2': 'Meh', '3': 'CircleMinus', '4': 'Smile', '5': 'Laugh' } },
  { id: 'weather', name: 'Weather', icons: { '1': 'CloudLightning', '2': 'CloudRain', '3': 'Cloud', '4': 'CloudSun', '5': 'Sun' } },
  { id: 'energy', name: 'Energy level', icons: { '1': 'BatteryLow', '2': 'BatteryMedium', '3': 'Battery', '4': 'BatteryCharging', '5': 'Zap' } },
  { id: 'heart', name: 'Heart / wellbeing', icons: { '1': 'HeartCrack', '2': 'HeartOff', '3': 'Heart', '4': 'HeartPulse', '5': 'HeartHandshake' } },
  { id: 'nature', name: 'Nature', icons: { '1': 'Sprout', '2': 'Leaf', '3': 'Trees', '4': 'Flower', '5': 'Flower2' } },
  { id: 'geometric', name: 'Simple geometric', icons: { '1': 'CircleX', '2': 'CircleMinus', '3': 'Circle', '4': 'CirclePlus', '5': 'CircleCheck' } },
  { id: 'temperature', name: 'Temperature', icons: { '1': 'ThermometerSnowflake', '2': 'Snowflake', '3': 'Thermometer', '4': 'SunMedium', '5': 'Flame' } },
  { id: 'gaming', name: 'Gaming / fun', icons: { '1': 'Skull', '2': 'Ghost', '3': 'Gamepad2', '4': 'Trophy', '5': 'Crown' } },
];

export function getIconComponent(name: string): IconComponent {
  return AVAILABLE_ICONS.find((i) => i.name === name)?.component ?? Tag;
}
