import {
  Activity,
  Apple,
  Baby,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Car,
  CircleCheck,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Dumbbell,
  Flame,
  Frown,
  Gift,
  Globe,
  Gamepad2,
  Headphones,
  Heart,
  Home,
  Laugh,
  Leaf,
  Lightbulb,
  Laptop,
  Map,
  Meh,
  MessageCircle,
  Moon,
  Music,
  Pencil,
  Phone,
  Pill,
  Pizza,
  Plane,
  ShoppingBag,
  Smile,
  SmilePlus,
  Sparkles,
  Star,
  Sun,
  Sunset,
  Tag,
  Target,
  ThumbsDown,
  ThumbsUp,
  TreePine,
  Trophy,
  Users,
  Utensils,
  Wind,
  Zap,
  ZapOff,
  Camera,
  Droplets,
  Eye,
  Footprints,
  Tv,
  Waves,
  PersonStanding,
} from 'lucide-react';

export const AVAILABLE_ICONS = [
  { name: 'Activity',      component: Activity,      label: 'Activity' },
  { name: 'Apple',         component: Apple,         label: 'Apple' },
  { name: 'Baby',          component: Baby,          label: 'Baby' },
  { name: 'Bike',          component: Bike,          label: 'Bike' },
  { name: 'BookOpen',      component: BookOpen,      label: 'Book' },
  { name: 'Brain',         component: Brain,         label: 'Brain' },
  { name: 'Briefcase',     component: Briefcase,     label: 'Briefcase' },
  { name: 'Camera',        component: Camera,        label: 'Camera' },
  { name: 'Car',           component: Car,           label: 'Car' },
  { name: 'CircleCheck',   component: CircleCheck,   label: 'Check' },
  { name: 'Clock',         component: Clock,         label: 'Clock' },
  { name: 'Cloud',         component: Cloud,         label: 'Cloud' },
  { name: 'CloudRain',     component: CloudRain,     label: 'Rain' },
  { name: 'Code',          component: Code,          label: 'Code' },
  { name: 'Coffee',        component: Coffee,        label: 'Coffee' },
  { name: 'Droplets',      component: Droplets,      label: 'Water' },
  { name: 'Dumbbell',      component: Dumbbell,      label: 'Workout' },
  { name: 'Eye',           component: Eye,           label: 'Eye' },
  { name: 'Flame',         component: Flame,         label: 'Flame' },
  { name: 'Footprints',    component: Footprints,    label: 'Walk' },
  { name: 'Frown',         component: Frown,         label: 'Sad' },
  { name: 'Gamepad2',      component: Gamepad2,      label: 'Gaming' },
  { name: 'Gift',          component: Gift,          label: 'Gift' },
  { name: 'Globe',         component: Globe,         label: 'Globe' },
  { name: 'Headphones',    component: Headphones,    label: 'Headphones' },
  { name: 'Heart',         component: Heart,         label: 'Heart' },
  { name: 'Home',          component: Home,          label: 'Home' },
  { name: 'Laptop',        component: Laptop,        label: 'Laptop' },
  { name: 'Laugh',         component: Laugh,         label: 'Laugh' },
  { name: 'Leaf',          component: Leaf,          label: 'Nature' },
  { name: 'Lightbulb',     component: Lightbulb,     label: 'Idea' },
  { name: 'Map',           component: Map,           label: 'Map' },
  { name: 'Meh',           component: Meh,           label: 'Meh' },
  { name: 'MessageCircle', component: MessageCircle, label: 'Chat' },
  { name: 'Moon',          component: Moon,          label: 'Moon' },
  { name: 'Music',         component: Music,         label: 'Music' },
  { name: 'Pencil',        component: Pencil,        label: 'Write' },
  { name: 'PersonStanding',component: PersonStanding,label: 'Person' },
  { name: 'Phone',         component: Phone,         label: 'Phone' },
  { name: 'Pill',          component: Pill,          label: 'Medicine' },
  { name: 'Pizza',         component: Pizza,         label: 'Food' },
  { name: 'Plane',         component: Plane,         label: 'Travel' },
  { name: 'ShoppingBag',   component: ShoppingBag,   label: 'Shopping' },
  { name: 'Smile',         component: Smile,         label: 'Smile' },
  { name: 'SmilePlus',     component: SmilePlus,     label: 'Happy+' },
  { name: 'Sparkles',      component: Sparkles,      label: 'Sparkles' },
  { name: 'Star',          component: Star,          label: 'Star' },
  { name: 'Sun',           component: Sun,           label: 'Sun' },
  { name: 'Sunset',        component: Sunset,        label: 'Sunset' },
  { name: 'Tag',           component: Tag,           label: 'Tag' },
  { name: 'Target',        component: Target,        label: 'Target' },
  { name: 'ThumbsDown',    component: ThumbsDown,    label: 'Dislike' },
  { name: 'ThumbsUp',      component: ThumbsUp,      label: 'Like' },
  { name: 'TreePine',      component: TreePine,      label: 'Tree' },
  { name: 'Trophy',        component: Trophy,        label: 'Trophy' },
  { name: 'Tv',            component: Tv,            label: 'TV' },
  { name: 'Users',         component: Users,         label: 'People' },
  { name: 'Utensils',      component: Utensils,      label: 'Eat' },
  { name: 'Waves',         component: Waves,         label: 'Waves' },
  { name: 'Wind',          component: Wind,          label: 'Wind' },
  { name: 'Zap',           component: Zap,           label: 'Energy' },
  { name: 'ZapOff',        component: ZapOff,        label: 'Tired' },
];

// Subset for mood icon selection
export const MOOD_ICONS = AVAILABLE_ICONS.filter(i =>
  ['Smile', 'SmilePlus', 'Laugh', 'Meh', 'Frown', 'Heart', 'Star', 'Zap',
   'ZapOff', 'ThumbsUp', 'ThumbsDown', 'Sun', 'Moon', 'Coffee', 'Flame',
   'Sparkles', 'Cloud', 'CloudRain', 'Sunset'].includes(i.name)
);

export function getIconComponent(name) {
  return AVAILABLE_ICONS.find(i => i.name === name)?.component ?? Tag;
}
